---
title: "lab 1 notes"
author: "Tiffanie Huang"
date: '2022-10-06'
output: html_document
---

```{r}
#Clear environment
rm(list=ls())

```

```{r}
 #Nernst equation

R <- 8.314
Tmp <- 310
Far <- 96490
Xout <- 50
Xin <- 500

nernst <- function(){
  volts <- (R*Tmp/Far)*log(Xout/Xin)
  return(volts*1000)
}

result <- nernst()
print(result)


#in lab, doing multiple ions instead of just one. increase concentration (Na becomes the only important thing) --> asymptotically approaching nernst potential.
```

```{r}

X <- 1:10
Y1 <- 2*X
Y2 <- 3*X
Y3 <- 4*X

plot(X, Y1, xlab="X", ylab="Y", main="Title",type = "o", col="black",xlim=c(1,10),ylim=c(2,40))
points(X,Y2, col="red")
lines(X, Y3, col="blue",type="o")
legend("bottomright",legend=c("2X","3X","4X"),fill=c("black","red","blue"))

```
```{r}
#initializing array with 0s, coinflip simulation for loop; plot results and abline mean
results <-rep(0,10)
for (i in 1:length(results)) {
  randNum <- runif(1)
  if (randNum < 0.5) {
    results[i] <- 1
  }
}


avg <- sum(results)/length(results)

plot(1:length(results),results,type="o")

#add straight line
abline(h=avg, col="red")


```

